# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL

    sudo apt-get update -y
    sudo apt-get install -y python-virtualenv

    sudo adduser --home /srv/myservice-app --system --disabled-password --group myservice-app
    sudo cp /vagrant/upstart/myservice-app.conf /etc/init/myservice-app.conf
    sudo apt-get update

    sudo mkdir /srv/myservice-app/releases
    sudo mkdir /srv/myservice-app/releases/init
    sudo ln -sfT /srv/myservice-app/releases/init /srv/myservice-app/current
    sudo chown -R myservice-app:myservice-app /srv/myservice-app

    SHELL
end
